# Generated by Django 3.2.3 on 2021-09-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanBo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cb', models.CharField(blank=True, max_length=30, null=True)),
                ('ngach_cb', models.CharField(blank=True, max_length=30, null=True)),
                ('gioi_tinh', models.CharField(blank=True, default='', max_length=3, null=True)),
                ('chuc_vu', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mst', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('ten_nnt', models.CharField(blank=True, max_length=120, null=True)),
                ('dia_chi', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cqt', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
