# Generated by Django 3.2.3 on 2021-10-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanBo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cb', models.CharField(default='', max_length=30)),
                ('gioi_tinh', models.CharField(default='', max_length=3)),
                ('chuc_vu', models.CharField(default='', max_length=30)),
                ('doan_tkt', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CanCu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_qd', models.CharField(default='', max_length=25)),
                ('ten_qd', models.CharField(default='', max_length=255)),
                ('ngay_qd', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LdPheDuyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_gt', models.CharField(default='', max_length=3)),
                ('ld_ten', models.CharField(default='', max_length=30)),
                ('ld_cv', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mst', models.CharField(default='', max_length=14, unique=True)),
                ('ten_nnt', models.CharField(default='', max_length=120)),
                ('dia_chi', models.CharField(default='', max_length=255)),
                ('cqt', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
