# Generated by Django 3.2.3 on 2022-01-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnt',
            name='cqt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nnt',
            name='dia_chi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nnt',
            name='mst',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nnt',
            name='ten_nnt',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
