# Generated by Django 3.2.3 on 2021-09-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanCu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_qd', models.CharField(default='', max_length=25)),
                ('ten_qd', models.CharField(default='', max_length=255)),
                ('ngay_qd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LD_phe_duyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ld_phong', models.CharField(default='', max_length=30)),
                ('ld_cuc', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='canbo',
            name='chuc_vu',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='canbo',
            name='gioi_tinh',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='canbo',
            name='ngach_cb',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='canbo',
            name='ten_cb',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='nnt',
            name='cqt',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='nnt',
            name='dia_chi',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nnt',
            name='mst',
            field=models.CharField(default='', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='nnt',
            name='ten_nnt',
            field=models.CharField(default='', max_length=120),
        ),
    ]
