# Generated by Django 3.2.3 on 2021-10-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canbo',
            name='ngach_cb',
        ),
        migrations.AlterField(
            model_name='canbo',
            name='chuc_vu',
            field=models.CharField(default='', max_length=30),
        ),
    ]
