# Generated by Django 3.2.3 on 2022-03-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0002_alter_canbo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancu',
            options={'permissions': (('cancu_view', 'CanCu View'), ('cancu_add', 'CanCu Add'), ('cancu_edit', 'CanCu Edit'), ('cancu_delete', 'CanCu Delete'))},
        ),
        migrations.AlterModelOptions(
            name='ldpheduyet',
            options={'permissions': (('ld_view', 'LdPheDuyet View'), ('ld_add', 'LdPheDuyet Add'), ('ld_edit', 'LdPheDuyet Edit'), ('ld_delete', 'LdPheDuyet Delete'))},
        ),
        migrations.AlterModelOptions(
            name='nnt',
            options={'permissions': (('nnt_view', 'NNT View'), ('nnt_add', 'NNT Add'), ('nnt_edit', 'NNT Edit'), ('nnt_delete', 'NNT Delete'))},
        ),
    ]
