# Generated by Django 3.2.3 on 2021-09-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0003_auto_20210924_0959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LD_phe_duyet',
            new_name='LdPheDuyet',
        ),
    ]
