# Generated by Django 3.2.3 on 2024-01-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0003_auto_20220315_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancu',
            name='ten_cc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
