# Generated by Django 3.2.3 on 2025-08-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0004_cancu_ten_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='canbo',
            name='vi_tri',
            field=models.CharField(default='', max_length=30),
        ),
    ]
