# Generated by Django 3.2.3 on 2021-09-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0004_rename_ld_phe_duyet_ldpheduyet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldpheduyet',
            old_name='ld_gioi_tinh',
            new_name='ld_gt',
        ),
    ]
