# Generated by Django 3.2.3 on 2025-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0005_canbo_vi_tri'),
    ]

    operations = [
        migrations.AddField(
            model_name='canbo',
            name='phong',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='canbo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cancu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ldpheduyet',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nnt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
