# Generated by Django 3.2.3 on 2021-09-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0005_rename_ld_gioi_tinh_ldpheduyet_ld_gt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancu',
            name='ngay_qd',
        ),
        migrations.RemoveField(
            model_name='cancu',
            name='so_qd',
        ),
        migrations.RemoveField(
            model_name='cancu',
            name='ten_qd',
        ),
        migrations.AddField(
            model_name='cancu',
            name='ld_cv',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cancu',
            name='ld_gt',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='cancu',
            name='ld_ten',
            field=models.CharField(default='', max_length=30),
        ),
    ]
