# Generated by Django 3.2.3 on 2021-09-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0006_auto_20210924_1618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CanCu',
            new_name='QD',
        ),
    ]
