# Generated by Django 3.2.3 on 2021-09-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tkt_qtr', '0007_rename_cancu_qd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QD',
            new_name='CanCuQD',
        ),
    ]
